server:
  port: 8080

spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: ${MARIADB_URL:jdbc:log4jdbc:mariadb://localhost:3306/brewnet}
    username: ${MARIADB_USERNAME:user}
    password: ${MARIADB_PASSWORD:password}

  jpa:
    generate-ddl: false
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
